per_page: 5
admin:
  product_size: "120x150"
  product_large_edit: "400x490"
products:
  per_page: 8
  product_size: "220x270"
  product_size_large: "300x400"
  default_product: "/assets/default.jpg"
users:
  ava_size: "50x50"
  ava_profile_size: "100x100"
  avatar: "/assets/avatar.jpg"
  comment_ava: "50x50"
order:
  product_size: "70x70"
  cart_size: "40x40"
slice:
  slice1: "/assets/slie5.jpg"
  slice2: "/assets/slice7.jpg"
  slice3: "/assets/slice2.jpg"
  size: "1050x400"
